FROM circleci/ruby:2.4.9-node-browsers AS base

USER root

RUN apt-get update -qq\
  && apt-get install -y vim\
  && rm -rf /var/lib/apt/lists/*

RUN bundle config git.allow_insecure true

EXPOSE 4000

WORKDIR /app
