Sage::Engine.routes.draw do
  get 'pages/item'

  get 'pages/breakout'
  get 'pages/generators'
  get 'pages/index'
  get 'pages/start'
  get 'pages/conventions'
  get 'pages/accessibility'
  get 'pages/browser'
  get 'pages/language'
  get 'pages/token'
  get 'pages/color'
  get 'pages/typography'
  get 'pages/grid'
  get 'pages/container'
  get 'pages/icon'
  get 'pages/elements'
  get 'pages/element'
  get 'pages/objects'
  get 'pages/object'
  get 'pages/utilities'
end
