Sage::Engine.routes.draw do
  get 'pages/item'
  get 'pages/status'
  get 'pages/breakout'
  get 'pages/index'
  get 'pages/token'
  get 'pages/color'
  get 'pages/typography'
  get 'pages/grid'
  get 'pages/container'
  get 'pages/icon'
  get 'pages/elements'
  get 'pages/element'
  get 'pages/objects'
  get 'pages/object'
  get 'pages/utilities'
end
